apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ include "flink.fullname" . }}
spec:
  image: hoale/flink:1.18
  imagePullPolicy: Always
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    state.backend: rocksdb
    state.backend.incremental: "true"
    process.working-dir: /opt/flink/flink-data/working-dir
    state.savepoints.dir: s3://flink/flink-data/savepoints
    state.checkpoints.dir: s3://flink/flink-data/checkpoints
    high-availability.type: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: s3://flink/flink-data/ha
    kubernetes.operator.job.autoscaler.enabled: "true"
    kubernetes.operator.job.autoscaler.stabilization.interval: 1m
    kubernetes.operator.job.autoscaler.metrics.window: 5m
    kubernetes.operator.job.autoscaler.target.utilization: "0.6"
    kubernetes.operator.job.autoscaler.target.utilization.boundary: "0.2"
    kubernetes.operator.job.autoscaler.restart.time: 2m
    kubernetes.operator.job.autoscaler.catch-up.duration: 5m
    pipeline.max-parallelism: "720"
  serviceAccount: {{ include "flink.serviceAccountName" . }}
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - mountPath: /opt/flink/flink-data
              name: flink-data
            - mountPath: /opt/flink/log
              name: flink-logs             
      volumes:
        - name: flink-logs
          emptyDir: { }
        - name: flink-data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "standard"
                resources:
                  requests:
                    storage: 20Gi          
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: job-manager-pod-template
      spec:
        containers:
          - name: flink-main-container
            env:
            - name: AWS_ENDPOINT_URL
              value: "http://aws-localstack.localstack:4566" 
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"              
          - name: flink-sql-gateway
            image: hoale/flink:1.18
            command: [ 'sh','-c','./bin/sql-gateway.sh start-foreground -Dsql-gateway.endpoint.rest.address=0.0.0.0' ]
            ports:
              - name: sqlgateway
                containerPort: 8083     
            env:
            - name: AWS_ENDPOINT_URL
              value: "http://aws-localstack.localstack:4566" 
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"                             
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: task-manager-pod-template
      spec:
        containers:
          - name: flink-main-container
            env:
            - name: AWS_ENDPOINT_URL
              value: "http://aws-localstack.localstack:4566"   
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"                     