apiVersion: v1
kind: Service
metadata:
  name: flink-rest-api
spec:
  ports:
    - port: 8081
      name: rest
      protocol: TCP
      targetPort: 8081
  selector:
    component: jobmanager
  type: LoadBalancer