apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "flink.fullname" . }}-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
    verbs:
      - '*'