apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "flink.fullname" . }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "flink.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "flink.serviceAccountName" . }}